version: "3.3"
services: 
  app:
    build: ./app
    links:
      - db
    ports: 
      - "80:80"
    restart: always
  db:
    image: mysql:latest
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
  
    